[variables]
gateway_token = "${password:32}"
auth_username = "dokploy"
auth_password = "${password:32}"

[config]
[[config.domains]]
serviceName = "openclaw"
port = 8080
host = "${domain}"

[config.env]
OPENCLAW_GATEWAY_TOKEN = "${gateway_token}"
OPENCLAW_GATEWAY_PORT = 18789
AUTH_USERNAME="${auth_username}"
AUTH_PASSWORD="${auth_password}"
OPENCLAW_GATEWAY_BIND="lan"
OPENCLAW_GATEWAY_ALLOWED_ORIGINS="https://${domain}"
OPENCLAW_GATEWAY_CONTROL_UI_ALLOWED_ORIGINS="https://${domain}"
OPENCLAW_GATEWAY_TRUSTED_PROXIES="10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
# Get here https://openrouter.ai/
OPENROUTER_API_KEY="YOUR-API-KEY"
